Repository thoth-station/thoth-ops-infra, pull requests merged in 2020-03, with the labels that each got.

#18 Installed remark-cli for MarkDownBear
  thoth-coala-ubi8/Dockerfile
  thoth-coala/Dockerfile
Labels: approved, size/XS

#19 Installed remark-lint to support remark-cli for MarkDownBear
  thoth-coala-ubi8/Dockerfile
  thoth-coala/Dockerfile
Labels: approved, size/XS

#20 Update s2i thoth to v0.10.0, relocked all python modules
  CHANGELOG.md
  thoth-black-ubi8/Dockerfile
  thoth-black-ubi8/Pipfile.lock
  thoth-black-ubi8/requirements.txt
  thoth-coala-ubi8/Dockerfile
  thoth-coala-ubi8/Pipfile.lock
  thoth-coala-ubi8/requirements.txt
  thoth-mypy-ubi8/Dockerfile
  thoth-mypy-ubi8/Pipfile.lock
  thoth-mypy-ubi8/requirements.txt
  thoth-pylint-ubi8/Dockerfile
  thoth-pylint-ubi8/Pipfile.lock
  thoth-pylint-ubi8/requirements.txt
  thoth-pytest-ubi8/Dockerfile
  thoth-pytest-ubi8/Pipfile.lock
  thoth-pytest-ubi8/requirements.txt
Labels: approved

#21 Zuul support for python3.7 pytest
  thoth-pytest-f31-py37/Dockerfile
  thoth-pytest-f31-py37/Pipfile
  thoth-pytest-f31-py37/Pipfile.lock
  thoth-pytest-f31-py37/pylintrc
  thoth-pytest-f31-py37/requirements.txt
Labels: approved

#22 Bump Thoth's s2i base image
  thoth-coala-ubi8/Dockerfile
  thoth-mypy-ubi8/Dockerfile
  thoth-pylint-ubi8/Dockerfile
  thoth-pytest-f31-py37/Dockerfile
  thoth-pytest-ubi8/Dockerfile
Labels: approved, size/S

#23 Use system pip when installing dependencies
  thoth-coala-ubi8/Dockerfile
  thoth-mypy-ubi8/Dockerfile
  thoth-pylint-ubi8/Dockerfile
  thoth-pytest-f31-py37/Dockerfile
  thoth-pytest-ubi8/Dockerfile
  thoth-pytest/Dockerfile
Labels: approved

#24 tag version update
  thoth-black-ubi8/Dockerfile
  thoth-coala-ubi8/Dockerfile
  thoth-mypy-ubi8/Dockerfile
  thoth-pylint-ubi8/Dockerfile
  thoth-pytest-f31-py37/Dockerfile
  thoth-pytest-ubi8/Dockerfile
Labels: approved
