Repository thoth-station/thoth-ops-infra, pull requests merged in 2020-05, with the labels that each got.

#25 create pre-commit image
  thoth-precommit-ubi8/Dockerfile
  thoth-precommit-ubi8/Pipfile
  thoth-precommit-ubi8/Pipfile.lock
  thoth-precommit-ubi8/requirements.txt
  thoth-precommit/Dockerfile
  thoth-precommit/Pipfile
  thoth-precommit/Pipfile.lock
  thoth-precommit/requirements.txt
Labels: approved, size/L

#26 Upgrade of base image version v0.12.4
  thoth-black-ubi8/Dockerfile
  thoth-coala-ubi8/Dockerfile
  thoth-mypy-ubi8/Dockerfile
  thoth-pylint-ubi8/Dockerfile
  thoth-pytest-f31-py37/Dockerfile
  thoth-pytest-ubi8/Dockerfile
Labels: size/S

#27 Base image pointed to Thoth ubi8 image
  thoth-precommit-ubi8/Dockerfile
Labels: approved, size/XS
