Repository thoth-station/thoth-ops-infra, pull requests merged in 2022-01, with the labels that each got.

#48 thoth pipeline github
  README.md
  thoth-pipeline-github/Containerfile
  thoth-pipeline-github/README.md
  thoth-precommit-ubi-py38/Dockerfile
  thoth-srcops/Dockerfile
Labels: size/M

#52 Build twine image from the repo
  .aicoe-ci.yaml
  README.md
  twine/Dockerfile
  twine/Pipfile
  twine/Pipfile.lock
Labels: size/L

#53 Include build package as it is standard for package build
  twine/Pipfile
  twine/Pipfile.lock
Labels: size/S
